spring:
  application:
    name: discoveryserver
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    export:
      prometheus:
        enabled: true
eureka:
  client:
    fetch-registry: false             #Bu ve altindaki kayit defteri kendisini tutmasin diye ekledik
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: discovery-server
